<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class AsyncThumbGen{

    public function __construct($pdfFile, $outputDir, $resolutions) {
        $this->url = $pdfFile;
        $this->outputDir = $outputDir;
        $this->resolutions = $resolutions;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

}
