<?php

require_once('ThumbGen.php');

class AsyncPdfConversion extends Worker
{
//extends Thread
    public function __construct($pdfFile, $outputDir, $resolutions) {
        $this->pdfFile = $pdfFile;
        $this->outputDir = $outputDir;
        $this->resolutions = $resolutions;
    }
//    public function __construct()
//    {
//
////        $this->resolutions[] = 120;
//    }

    function run()
    {

//      parent::run(); // TODO: Change the autogenerated stub
//        $this->load->library('thumbnailGenerator');
//        $this->load->library('email');
        $generator = new ThumbGen();
        $pngFiles = $generator->makePdfPages($this->pdfFile, $this->outputDir, (array)$this->resolutions);
//        log_message('debug', 'PNG files: ' . print_r($pngFiles, true));
        $generator->makeThumbnail($pngFiles[$this->resolutions[0]][1], $this->outputDir . '/cover.jpg', '200x293');
    }

}

?>