<?php

class PDFWork extends Worker
{
//extends Thread
//extends Worker
//but Threaded works with used Pool
    private $complete;
    private $init;
    private $task;
    private $pdfFile;
    private $outputDir;
    private $resolutions;
    private $generator;
    private $taskBase;
    public function __construct() {
        $this->complete = false;
        $this->init = false;
    }
    function initWork($generator, $task, $taskBase) {

        $this->task = $task;
        $this->pdfFile = $task->pdfFile;
        $this->outputDir = $task->outputDir;
        $this->resolutions = $task->resolutions;
        $this->generator = $generator;
        $this->taskBase = $taskBase;
        $this->complete = false;
        $this->init = true;
    }
    function run()
    {
        if(!$this->init){
            return;
        }
        $generator = $this->generator;
//      parent::run(); // TODO: Change the autogenerated stub
        $this->taskBase->setAsActive($this->task->id);
        $pngFiles = $generator->makePdfPages($this->pdfFile->full_path, $this->outputDir, (array)$this->resolutions);
        $generator->makeThumbnail($pngFiles[$this->resolutions[0]][1],
            $this->outputDir . '/cover.jpg', '200x293');
        $this->task->job->save($pngFiles);
        $this->taskBase->setAsDone($this->task->id);
        $this->complete = true;
        if($this->isStarted()){
            $this->shutdown();
        }
//        $this->shutdown();
    }
    public function isComplete() {
        return $this->complete;
    }
    public function getTask() {
        return $this->task;
    }

}